version: "2.4"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data:/docker-entrypoint-initdb.d/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=root
      - POSTGRES_ENCODING=UTF-8  
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports: 
        - "16543:80"
    depends_on: 
        - postgres    
